language: python
python:
  - "3.6"
install:
  - pip install ansible==2.8.6 molecule[gce] apache-libcloud
script:
  - ls -la
  - molecule test --scenario-name gce
after_script:
  - molecule destroy --scenario-name gce
before_install:
  - openssl aes-256-cbc -K $encrypted_7b81dd4d66f3_key -iv $encrypted_7b81dd4d66f3_iv
    -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar
  - mv google_compute_engine /home/travis/.ssh/
  - chmod 0600 /home/travis/.ssh/google_compute_engine
env:
  global:
    - USER=travis
    - secure: mHMVZdaNcfkC5XyJofJ4DgCiOsbs8t7lgX0j9X4JSvVhYLbxeb9gyXI4u1xv14gyHr7+LDO3rhEhPp7DOLMpqUoSCgmd6pY/sSIjZLXA5GfHyxxJESgTormPnCEE6kGEliizCZxa0e8kqfZbBAdTChHXuSo/Lu0era9HVa7NEsC14rVrw8+ktIhyXsmwnXq+AjvfU4upH1H9b0WS4dqRLR9w8n7NzkrwrS+ktScTV8WSGi7Yo12g2qMDqnvZ94doWO17lQ824prR09GwqFJttF9x9mdj3V3xTAguEUnBwToyfOdG635CcMnhD1GOa02c7vf5J8FUWAJo/bTtKW2IHwZCbRlp00bep3yK8u6+m+9db6lg7cdhaZJtZo3LOalr4YQPzNmPufvpIL3XOFw1NxtMclZHWn/HbzJy2X0hULTeF6Rlfb3s/FS4QfVR4OjwveIZpo46tx1olAxGqMQGgiyAlpSe6CMt5YxVdYgu21w1OjUBvqd07ggBJNkQBAw3sS34n+5+lT9Rn5ayhotjce2ggXzdkjv/V4IUyMEkh+qVCAjFfTk0Ry7sbhLwv/ko6iLP+JezsLMIVcwTQSNxH5+/xDzEkcb90J36V5nw+OA4cMjwuwp7P5yUll/uM4bbbZUcnlfHu2XzZ2yZrtryvLgHdt6vkvsp1ipmLFd1eYY=
    - secure: pEkdIKIgFlnszbR/7ERGxfAVGo3Is4FqEfGjMBoV745JR/OMDxfglBlTj68EhEHOdmBNBF/wKL/wcqe/OsBKFDIOugiW6CeaH8PoBn+XzRzT/ytHFf/UjtI2HGK1DqGk/o/X3s0gyGJ9YONwvlbC7mfrpIpDNP/1g12FDNXAjvGayfNhOFm67LZ+FX+uDBQiy6GM+8mTRrA2W+OsbSKSHKqadxXALAEt9/ASlyJ6HSkVG6YQP8X0ppLyKnVftz68Gr2NE9vhAYnTOdP5Wd2RFyTQe2thA90GrFD5zDYPE+vT3cuSPGjQL2AINRv+jT8As5bBfYHnWC9nfFTJqBFjgK+Yg8g7fBBhOJe21lLY5+8CWnSWj8uyXTcjP8V918E2tTQHUd9qbbNW5NMBiRXhg+rURQwUSDnAAF/yBZTD+XOSOme1pjl7W3GtdQ23u3trdtqmMalAGelG0bm0uY5WsKjTnJc6pDFmlSE5gXZi2yaPLgtQ2hFAZJXVOJkmFO0PItHKeLJ4suE1/x7CQ++dQrxPlnCURkgXntdXnBWMH2Bp1m1fTykEhM9gOETyCHhdoQVHGyIhzCUf0AfZsPsVw7z/VbqaHxt8oF954zjscE/quUVobzDVLvZDumgmZycZFk/5zRxvH+xwQfjvAv+hEQAUF3l+y/ENxEQlW46gxBk=
    - secure: xxrbSOgD9jhNDLthOvd6pynUG0Pmf7yOdPRY46zbQr2xCo+Lfvqm3C7VOOwCp+dGlMqrRUhEkq8BXQDi64qzoL3xQ8rwoTUcqTdtYUZbXc6t4ZxXHy4OqkkY1jGRUM5lyCkc2NNZAy4FvhD5GoZvn+OhXpfD7eIDLUUzUOWoQwcor2OYQ6AQmKqIba+TU7+Q+fWelfUHXvcQfnmXd5dBlZrkQMsrXq+AwRgDZoUxVlpuuEVOm6sbC5EELRdjMHAn5sk44I+keXu65E+L52tT5sACOld5gq3JrsUg/nvXy+OpV/y3o+K6ie44YiXEDzBs/pPXIZlZAsdjSef1E5hBrf7WqxvbnBcUeXt/fDJ4Ao/0ivEvI395VSR2hykRxfm47xPEi1/zlzJiCY9bGN7Qc5Ez6aAGD0ObALRrws/3dBNC7no0YqsZvFzaNqEXfOjw+a4wnd4GzslCymOI+ltm8vOZNabPdA0P1ziP5lbFwdBv4cDBZiteE2b3gNOr0sMkd0uGvLmdxuIXxrxEK82axa1rxcohGSi/r5YKzBbnGf1owj7w4UtbNttmmoUbdx44Hk5707NbRDWf44hLSx8ArR/3JNrB9psJHg1/q+xxZo+5tRNInB+QAkiVI6QGrKhY82/YaHHkOCkDqXRkjtkeqzPHNRGw2HbDjW9ZgjjPBBk=
