---
- name: Provide repository apt key
  apt_key:
    url: "{{ key_url }}"
    state: present

- name: Add repository
  apt_repository:
    repo: "deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/{{ mongodb_version }} multiverse"
    state: present
    update_cache: yes
    filename: "mongodb-org-{{ mongodb_version }}"

- name: Install package
  apt:
    name: "{{ packages }}"
    state: present

- name: Start mongod service on boot
  systemd:
    name: mongod
    enabled: yes
    state: started
